#!/bin/sh -e
openssl genrsa -out trusted.key 2048
openssl req -new -x509 -days 3650 -key trusted.key -out trusted.crt

openssl genrsa -out untrusted.key 2048
openssl req -new -x509 -days 3650 -key untrusted.key -out untrusted.crt

openssl pkcs12 -export -in trusted.crt -out trusted.p12 -nokeys -cacerts
