#!/bin/sh -e
openssl genrsa -out cert.key 4096
openssl req -new -key cert.key -out cert.csr
openssl x509 -req -days 365 -in cert.csr -signkey cert.key -out cert.crt
openssl pkcs12 -export -out cert.p12 -in cert.crt -inkey cert.key
keytool -importkeystore -destkeystore cert.jks -srckeystore cert.p12 -srcstoretype PKCS12
